POST http://127.0.0.1:8000/api/invoices/
Content-Type: application/json


{
    "topic": "Invoice for services rendered",
    "echeance": "2023-10-01",
    "client": 1,
    "tax": "False",
    "type_tax": "ISB",
    "number":1,
    "payment_mode": "Credit Card",
    "designations": [
        {
            "designation_title": "Web Development",
            "designation_details": "Development of company website",
            "designation_unit_price": "1000.00",
            "designation_quantity": 2
        },
        {
            "designation_title": "SEO Services",
            "designation_details": "Search engine optimization",
            "designation_unit_price": "500.00",
            "designation_quantity": 1
        }
    ]
}